name: Node
env:
    OPERATOR_KEY: ${{ secrets.OPERATOR_KEY }}
    OPERATOR_ID: ${{ secrets.OPERATOR_ID }}

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-cache-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cache-${{ matrix.node-version }}-

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup protoc
      uses: arduino/setup-protoc@v1.1.0
      with:
        version: 3.11.1
    
    - run: yarn
    
    - run: yarn test:unit
    
    - run: yarn test:e2e

    - run: yarn lint
